[book]
title = "Immer in Bewegung Documentation â€” 3rd gen DRAFT"
authors = ["plans-coding"]
language = "en"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fab-github"
