[book]
title = "Immer in Bewegung Documentation â€” 3rd gen"
authors = ["plans-coding"]
language = "en"

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/plans-coding/immer-in-bewegung/"
git-repository-icon = "fab-github"
